### PR TITLE
feat: added tool to debug session serialization

### LINKED ISSUE #30: Add a tool to help debug serialization issues during development mode
To help developers spot serialization issues during development, we may add a feature that performs serialization/deserialization for every request.

I could perhaps be a `RequestHandler`, installed only if the application is running in development mode and if it specifically activated through a configuration property (e.g. `vaadin.serialization.enableDebug`).

The handler should catch potential exceptions and log them on console.
It may be useful to automatically set the `-Dsun.io.serialization.extendedDebugInfo=true` system property during test serialization test and reset it once the handler completes its work.

We may also consider, if possible, to make serialization results visible also on the browser.

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

This change adds a RequestHandler that can be activated during
development to check if HTTP session is serializable.
Activation is done by registering the
SerializationDebugRequestHandler.InitListener and setting the
'devmode.sessionSerialization.enabled' property to true.
In SpringBoot projects, the tool is automatically installed
in development, if the above condition is met.

Fixes #30

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mcollovati** [comment]
PR is based on `spikes/deserialize-attach-transients` branch
I'll rebase it on main or create a new one once the other branch is merged.

**Comment by tarekoraby** [comment]
>  For Spring projects, the init listener is registered automatically if the application is running in development mode and the debug feature is enabled in application.properties.

Will there be a way to disable this feature for a Spring project?

**Comment by tarekoraby** [comment]
Thanks for clarifying. But if feasible, I think it would be better to enable this feature automatically in a Spring Boot project once the Kit's dependency is added—kind of like what happens if I add Spring Security to my project.

**Comment by mcollovati** [comment]
We can add the bean definition in the Kit and make it conditional on properties `vaadin.productionMode` and `devmode.sessionSerialization.enabled`.
Maybe @heruan has some better insight

**Comment by heruan** [comment]
> We can add the bean definition in the Kit and make it conditional on properties `vaadin.productionMode=false` and `devmode.sessionSerialization.enabled=true`. Maybe @heruan has some better insight

I'd go for that, setting `devmode.sessionSerialization.enabled=true` already suggests what the developer is going after.

Does this also automatically enable the `extendedDebugInfo` property? That amount of log might be unexpected, so probably we should just suggest to enable the property in the docs.

**Comment by mcollovati** [comment]
> Does this also automatically enable the `extendedDebugInfo` property? That amount of log might be unexpected, so probably we should just suggest to enable the property in the docs.

No, it does not.
Other than log entries, there are other potential issues because `toString()` is used to represent objects.
For example, Hibernate `PersistenList.toString()` may attempt to load the lazy collection
See comments on the issues https://github.com/vaadin/azure-kit/issues/30#issuecomment-1305180249

In the documentation there is this paragraph

```
When facing exceptions on serialization phase, it may be useful set the `sun.io.serialization.extendedDebugInfo` system property to make Java serialization verbose.
However, be aware that to represent the objects beans serialized, the `toString()` method is used, and this in rare cases may cause issues not related to serialization.
For example, Hibernate [classname]`PersistentList.toString()` forces initialization of the lazy loaded collection.
If this happens without an active Hibernate session, an exception is thrown.
```

**Comment by heruan** [comment]
Good enough if the docs mention it and also explain the side effects! The bean definition based on a property condition would still be useful in development mode.

**Comment by mcollovati** [comment]
Just to clarify, the `devmode.sessionSerialization.enabled=true` already exists in Flow, and is used to enable serialization of UIs inside VaadinSession, that by default are skipped.

**Comment by heruan** [comment]
> Just to clarify, the `devmode.sessionSerialization.enabled` property already exists in Flow, and is used to enable serialization of UIs inside VaadinSession, that by default are skipped.

Should have our own property to enable the request handler, even if the meaning is similar to that one?

**Review by heruan — APPROVED** [review]
Since the Flow property would still be needed to be set, let's use that one. We'll make sure documentation is clear about the need to enable it to run the serialization debug helper.

**Pull request merged**
